version: "3.2"

services:
#node Container
  senha-moodle:
    image: ltbproject/self-service-password # https://hub.docker.com/r/ltbproject/self-service-password
    ports:
      - "7777:80"  #local/application
    volumes: 
      - ./data/config/config.inc.local.php:/var/www/conf/config.inc.local.php
      - ./data/lang/pt-BR.inc.php:/var/www/lang/pt-BR.inc.php
      - ./data/html/css/self-service-password.css:/var/www/html/css/self-service-password.css
      - ./data/html/images:/var/www/html/images
      - ./data/templates/menu.tpl:/var/www/templates/menu.tpl
      - ./data/templates/footer.tpl:/var/www/templates/footer.tpl
      - ./data/templates/header.tpl:/var/www/templates/header.tpl
      - ./data/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf

#     networks:
#       - traefik-net
#       -   senha-moodle-net
#     deploy:
#       mode: replicated
#       replicas: 1
#       placement:
#         constraints: [node.role == manager]
#       labels:
#         - "traefik.docker.network=traefik-net"
#         - "traefik.frontend.rule=Host:senha-moodle.sertao.ifrs.edu.br"
#         - "traefik.port=80" # application port
#         - "traefik.backend=senha-moodle"

# networks:
#   traefik-net:
#      external: true
#   senha-moodle-net:
#     driver: overlay

volumes:
  data:
    driver: local


# Comando para executar o container
# docker container run -d --name senha-moodle -p 7777:80 senha-moodle
# docker stack deploy -c senha-moodle.yml senha-moodle